export enum PERMISSIONS {
    IS_OWNER = 'IS_OWNER',
    ACCOUNT_ADD_PREMIUM = 'ACCOUNT_ADD_PREMIUM',
    ACCOUNT_EDIT_PREMIUM = 'ACCOUNT_EDIT_PREMIUM',
    ACCOUNT_DELETE_PREMIUM = 'ACCOUNT_DELETE_PREMIUM',
    ACCOUNT_GET_PREMIUM = 'ACCOUNT_GET_PREMIUM',

    LIBRARY_ADD_PREMIUM = 'LIBRARY_ADD_PREMIUM',
    LIBRARY_EDIT_PREMIUM = 'LIBRARY_EDIT_PREMIUM',
    LIBRARY_DELETE_PREMIUM = 'LIBRARY_DELETE_PREMIUM',
    LIBRARY_GET_PREMIUM = 'LIBRARY_GET_PREMIUM',

    RATE_DELETE_PREMIUM = 'RATE_DELETE_PREMIUM',
    RATE_EDIT_PREMIUM = 'RATE_EDIT_PREMIUM',

    BOOK_ADD_PREMIUM = 'BOOK_ADD_PREMIUM',
    BOOK_EDIT_PREMIUM = 'BOOK_EDIT_PREMIUM',
    BOOK_DELETE_PREMIUM = 'BOOK_DELETE_PREMIUM',
    BOOK_ADD_PRESS = 'BOOK_ADD_PRESS',
    BOOK_EDIT_PRESS = 'BOOK_EDIT_PRESS',
    BOOK_DELETE_PRESS = 'BOOK_DELETE_PRESS',

    COMMENT_ADD_PREMIUM = 'COMMENT_ADD_PREMIUM',
    COMMENT_EDIT_PREMIUM = 'COMMENT_EDIT_PREMIUM',
    COMMENT_DELETE_PREMIUM = 'COMMENT_DELETE_PREMIUM',
}