export enum TPERMISSIONS {
    IS_OWNER = 'IS_OWNER',

    BOOK_ADD_PREMIUM = 'BOOK_ADD_PREMIUM',
    BOOK_EDIT_PREMIUM = 'BOOK_EDIT_PREMIUM',
    BOOK_DELETE_PREMIUM = 'BOOK_DELETE_PREMIUM',
    BOOK_ADD_PRESS = 'BOOK_ADD_PRESS',
    BOOK_EDIT_PRESS = 'BOOK_EDIT_PRESS',
    BOOK_DELETE_PRESS = 'BOOK_DELETE_PRESS',
    BOOK_PRESS_PREMIUM ='BOOK_PRESS_PREMIUM',   //++

    PERSON_EDIT_PREMIUM = 'PERSON_EDIT_PREMIUM',   //++
    PERSON_DELETE_PREMIUM = 'PERSON_DELETE_PREMIUM',   //++
    PERSON_GET_PREMIUM = 'PERSON_GET_PREMIUM',   //++
    PERSON_ADD_PREMIUM = 'PERSON_ADD_PREMIUM',        //++

    USER_DELETE_PREMIUM = 'USER_DELETE_PREMIUM',   //++
    USER_GET_PREMIUM = 'USER_GET_PREMIUM',   //++
    USER_EDIT_PREMIUM = 'USER_EDIT_PREMIUM',   //++

    COMMENT_ADD_PREMIUM = 'COMMENT_ADD_PREMIUM',
    COMMENT_EDIT_PREMIUM = 'COMMENT_EDIT_PREMIUM',
    COMMENT_DELETE_PREMIUM = 'COMMENT_DELETE_PREMIUM',
    COMMENT_GET_PREMIUM = 'COMMENT_GET_PREMIUM',   //++
    COMMENT_ACTION_DELETE_PREMIUM = 'COMMENT_ACTION_DELETE_PREMIUM',    //++

    //
    ORDER_ADD_PREMIUM = 'ORDER_ADD_PREMIUM',    //++   
    ORDER_ADD_PRESS = 'ORDER_ADD_PRESS',    //++
    ORDER_GET_PREMIUM = 'ORDER_GET_PREMIUM',    //++
    ORDER_EDIT_PREMIUM = 'ORDER_EDIT_PREMIUM',    //++
    ORDER_DELETE_PREMIUM = 'ORDER_DELETE_PREMIUM',    //++

    ORDER_ITEM_GET_PREMIUM = 'ORDER_ITEM_GET_PREMIUM',   //++
    ORDER_ITEM_EDIT_PREMIUM = 'ORDER_ITEM_EDIT_PREMIUM',   //++
    ORDER_ITEM_DELETE_PREMIUM = 'ORDER_ITEM_DELETE_PREMIUM',   //++

    ORDER_CHECKOUT_PREMIUM ='ORDER_CHECKOUT_PREMIUM',   //++
    //

    PRICE_ADD_PREMIUM = 'PRICE_ADD_PREMIUM',   //++
    PRICE_GET_PREMIUM = 'PRICE_GET_PREMIUM',   //++
    PRICE_EDIT_PREMIUM = 'PRICE_EDIT_PREMIUM',   //++
    PRICE_DELETE_PREMIUM = 'PRICE_DELETE_PREMIUM',   //++
    PRICE_ADD_PRESS = 'PRICE_ADD_PRESS',   //++
    PRICE_EDIT_PRESS = 'PRICE_EDIT_PRESS',   //++
    PRICE_DELETE_PRESS = 'PRICE_DELETE_PRESS',   //++

    ACCOUNT_ADD_PREMIUM = 'ACCOUNT_ADD_PREMIUM',
    ACCOUNT_EDIT_PREMIUM = 'ACCOUNT_EDIT_PREMIUM',
    ACCOUNT_DELETE_PREMIUM = 'ACCOUNT_DELETE_PREMIUM',
    ACCOUNT_GET_PREMIUM = 'ACCOUNT_GET_PREMIUM',

    LIBRARY_ADD_PREMIUM = 'LIBRARY_ADD_PREMIUM',
    LIBRARY_EDIT_PREMIUM = 'LIBRARY_EDIT_PREMIUM',
    LIBRARY_DELETE_PREMIUM = 'LIBRARY_DELETE_PREMIUM',
    LIBRARY_GET_PREMIUM = 'LIBRARY_GET_PREMIUM',

    RATE_GET_PREMIUM = 'RATE_GET_PREMIUM',   //++
    RATE_DELETE_PREMIUM = 'RATE_DELETE_PREMIUM',
    RATE_EDIT_PREMIUM = 'RATE_EDIT_PREMIUM',

    TRANSACTION_DELETE_PREMIUM = 'TRANSACTION_DELETE_PREMIUM',  //++
    TRANSACTION_GET_PREMIUM = 'TRANSACTION_GET_PREMIUM',     // ++ 
    TRANSACTION_ADD_PREMIUM = 'TRANSACTION_ADD_PREMIUM',   //++

    CHAT_DELETE_PREMIUM = 'CHAT_DELETE_PREMIUM',   //++
    CHAT_GET_PREMIUM = 'CHAT_GET_PREMIUM',   //++
    CHAT_EDIT_PREMIUM = 'CHAT_EDIT_PREMIUM',   //++

    DISCUSSION_GROUP_PREMIUM = 'DISCUSSION_GROUP_PREMIUM',   //++
    DISCUSSION_MEMBER_PREMIUM = 'DISCUSSION_MEMBER_PREMIUM',   //++

    FOLLOW_DELETE_PREMIUM = 'FOLLOW_DELETE_PREMIUM',     //++
}

