export enum SORT {
    title = 'title+',
    title_ = 'title-',
    type = 'type+',
    type_ = 'type-',
    creator = 'creator+',
    creator_ = 'creator-',
    creation_date = 'creation_date+',
    creation_date_ = 'creation_date-',
    modifier = 'modifier+',
    modifier_ = 'modifier-',
    modification_date = 'modification_date+',
    modification_date_ = 'modification_date-',
    pub_year = 'pub_year+',
    pub_year_ = 'pub_year-',
    full_name = 'full_name+',
    full_name_ = 'full_name-',
    is_legal = 'is_legal+',
    is_legal_ = 'is_legal-',
    cell_no = 'cell_no+',
    cell_no_ = 'cell_no-',
    phone = 'phone+',
    phone_ = 'phone-',
    username = 'username+',
    username_ = 'username-',
    body = 'body+',
    body_ = 'body-',
    likes = 'likes+',
    likes_ = 'likes-',
    reports = 'reports+',
    reports_ = 'reports-',
    status = 'status+',
    status_ = 'status-',
    total_price = 'total_price+',
    total_price_ = 'total_price-',
}

