export const ar = {
    login: "تسجيل الدخول",
    register: "تسجيل",
    sign_in: 'تسجيل الدخول',
    app_title: 'فروشگاه کتاب',
    app_title_: 'عنوان برنامه',
    app_logo: 'فروشگاه کتاب',
    brand_name: 'فروشگاه کتاب',
    sign_in_bookstore_account: 'با حساب فروشگاه کتاب خود داخل شوید',
    forgot_password: 'رمز عبورتان را فراموش کردید؟',
    msg: {
        ui: {
            msg1: 'عملیات با موفقیت انجام شد.',
            msg2: 'خطا رخ داد.',
            msg3: 'ثبت نام با موفقیت انجام شد، به صفحه ورود منتقل می شوید.',
            msg4: 'رمز عبور با موفقیت تغییر کرد، به صفحه ورود منتقل می شوید.',
            your_rate_submited: 'رتبه شما ثبت شد',
            your_comment_submited: 'نظر شما ثبت شد',
            your_comment_will_be_removed_continue: 'نظر شما حذف خواهد شد، تایید می کنید؟',
            no_network_connection: 'خطا رخ داد، لطفا دسترسی اینترنت خود را بررسی کرده و مجددا تلاش کنید.',
            new_vesion_available_update: 'نسخه جدیدی از برنامه موجود است، می توانید بروز کنید.',
            item_will_be_removed_continue: 'رکورد مورد نظر حذف خواهد شد، تایید می کنید؟',
        },
        back: {
            user_already_exists: 'کاربر از قبل وجود دارد.',
            no_valid_activation_code: 'کد فعالسازی شما منقضی شده است، برای دریافت کد جدید ارسال مجدد را بفشارید.',
            wrong_activation_code: 'کد فعالسازی اشتباه است.',
            already_has_valid_key: 'امکان ارسال مجدد پیامک {0} ثانیه دیگر برای شما فعال می شود.',
            message_not_sent: 'ارسال پیامک با خطا مواجه شد، لطفا مجددا تلاش کنید.',
            cell_no_required: 'تلفن همراه الزامی است.',
            message_sent: 'پیام با موفقیت برای تلفن همراه ارسال شد.',
            username_exists: 'نام کاربری تکراری است، لطفا نام کاربری دیگری انتخاب کنید.',
            signup_token_not_exists: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            invalid_signup_token: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            token_invalid: 'مجددا وارد شوید',
            token_expired: 'token expired',
            delete_failed: 'deleting failed',
            get_failed: 'getting failed',
            auth_decoding_failed: 'Authentication decoding failed',
            commit_failed: 'سرویس دهنده با خطا مواجه شد.',
            no_auth: 'no auth found',
            invalid_username: 'نام کاربری یا رمز عبور اشتباه است.',
            invalid_enum: 'enum is not correct  type',
            not_found: 'entity not found',
            invalid_persons: 'there is invalid person id in list',
            addition_error: 'adding model to database failed',
            username_cellno_required: 'برای دریافت رمز عبور نام کاربری یا شماره موبایل را وارد کنید',
            invalid_user: "با اطلاعات وارد شده کاربری وجود ندارد",
            invalid_code: 'کد تایید اشتباه است.',

            filter_required: 'filter object is not in data',
            upload_failed: 'بارگذاری فایل با مشکل مواجه شد.',
            invalid_entity: 'entity is not right instance of Class',
            access_denied: 'دسترسی به این مورد امکانپذیر نمی باشد',
            already_liked: 'شما قبلا این نظر را مفید اعلام کردید.',
            comment_not_found: 'نظر یافت نشد.',
            already_reported: ' شما قبلا این نظر را گزارش کردید.',
            report_not_found: 'گزارشی از شما برای این نظر یافت نشد.',
            parent_not_found: 'نظر مرتبط با این نظر یافت نشد.',
            follow_denied: 'کاربر نمی تواند خودش را دنبال کند.',
            already_follows: 'شما از قبل این مورد را دنبال کرده اید.',
            missing_requiered_field: 'موارد ضروری را پر کنید',
            already_rated: 'کاربر از قبل به کتاب رتبه داده است.',
            already_exists: 'از قبل وجود دارد.',
            credit_debit_error: 'اعتبار و بدهی هر دو نمی تواند همزمان مقدار داشته باشد.',
            no_price_found: 'برای کتاب قیمتی وجود ندارد.',
            discount_is_float: 'تخفیف باید عدد وارد شود.',
            insufficiant_balance: 'موجودی حساب شما از رسید کمتر است',
            user_has_no_account: 'کاربر حسابی ندارد',
            order_invoiced: 'سفارش فاکتور شده و قابل حذف نمی باشد.',
            commit_error: 'خطا در نوع داده ارسالی',
            person_has_books: 'این شخص در حال حاظر نقش در کتاب(ها) دارد.',
            book_not_in_lib: 'کتاب در کتابخانه شما وجود ندارد و نمی توان آن را به کلکسیونی افزود.',
        }
    },
    validation: {
        minLength: 'حداقل {value} کاراکتر',
        mobileFormat: 'فرمت موبایل صحیح نیست',
        smsCodeFormat: 'فرمت کد صحیح نیست.',
        confirmPassword: 'رمز عبور با تایید آن همخوانی ندارد.',
    },
    username: 'نام کاربری',
    password: 'رمز عبور',
    name: 'نام',
    lastname: 'نام خانوادگی',
    phone: 'تلفن',
    address: 'آدرس',
    mobile: 'تلفن همراه',
    confirm_password: 'تایید رمز عبور',
    invalid_value: 'مقدار نامعتبر است',
    required_field: 'فیلد ضروری است',
    Show_password: 'نمایش رمزعبور',
    login_agree_msg: {
        a: 'با انتخاب "ورود" شما موافقت خود با {0} و {1} را تایید می کنید.',
        b: 'مطالب فروشگاه کتاب',
        c: 'شرایط استفاده از نرم افزار'
    },
    new_to_Bookstore: 'تازه واردید؟',
    need_free_bookstore_account: "احتیاج به یک حساب کاربری رایگان فروشگاه کتاب دارید.",
    register_your_mobile_number: 'شماره تلفن همراه خود را وارد کنید',
    submit: 'ثبت',
    already_have_bookstore_account: 'از قبل حساب کاربری فروشگاه کتاب دارید؟',
    verification_code_sended_via_sms_submit_here: 'کد تایید برای شما پیامک شد، لطفا در اینجا ثبت کنید.',
    verification_code: 'کد تایید',
    create_an_account: 'ساخت حساب کاربری',
    send_again: 'ارسال مجدد',
    send_again_activationCode: 'ارسال مجدد کد فعالسازی',
    in: 'در',
    second: 'ثانیه',
    search: 'جستجو',
    home: 'خانه',
    library: 'کتابخانه',
    store: 'فروشگاه',
    more: 'بیشتر',
    recomended_for_you: 'پیشنهادی برای شما',
    new_release_in_bookstore: 'نسخه های جدید در کتابفروشی',
    more_by_writer: 'بیشتر از {0}',
    helen_hardet: 'هلن هاردت',
    it_will_be_launched_soon: 'بزودی راه اندازی خواهد شد.',

    read_now: 'الان بخوان',
    view_in_store: 'نمایش در فروشگاه',
    add_to_collection: 'اضافه کردن به کلکسیون',
    mark_as_read: 'به عنوان خوانده شده علامت بزن',
    share_progress: 'اشتراک گذاری پیشرفت',
    recommend_this_book: 'پیشنهاد دادن کتاب',
    remove_from_device: 'حذف از دستگاه',
    remove_from_home: 'حذف از خانه',
    loading_with_dots: 'درحال بارگذاری...',
    retry: 'تلاش مجدد',
    title: 'عنوان',
    return: 'بازگشت',
    insert_username_or_mobile: 'نام کاربری یا تلفن همراه خود را وارد کنید',
    reset_password: 'تغییر رمز عبور',
    add_to_list: 'به لیست اضافه کن',
    log_out: 'خروج',
    sync: 'همگام سازی',
    read_listen_with_audible: 'خواندن و گوش دادن با صدا',
    book_update: 'بروزرسانی کتاب',
    create:"ایجاد",
    reset:"تنظیم مجدد",
    back:"بازگشت",
    reading_insights: 'خواندن عمیق',
    settings: 'تنظیمات',
    info: 'اطلاعات',
    help_feedback: 'کمک و بازخورد',
    about_bookstore_edition: 'درباره نسخه کتابفروشی',
    Length: 'اندازه',
    pages: 'صفحه',
    from_the_editor: 'از ویراستار',
    about_this_item: 'درباره این محصول',

    description: 'توضیحات',
    product_description: 'توضیحات محصول',
    review: 'نظر',
    reviews: 'نظرات',
    review_s: 'نظر',
    about_the_author: 'درباره نویسنده',
    features_details: 'ویژگی ها و جزئیات',
    product_details: 'جزئیات محصول',
    publication_date: 'تاریخ انتشار',
    publisher: 'ناشر',
    language: 'زبان',
    bookstore_sales_rank: 'رتبه فروش در کتابفروشی',
    follow: 'دنبال کردن',
    unfollow: 'دنبال نکردن',
    customer_review: 'نظر مشتری ها',
    customer_vote_s: 'رای مشتری ها',
    read_reviews_that_mention: 'خواندن نظر های ذکر شده',
    see_more: 'بیشتر ببینید',
    see_less: 'کمتر ببینید',
    top_reviews: 'نظر های برتر',
    verified_purchase: 'خرید تایید شده',
    format: 'قالب',
    bookstore_edition: 'نسخه کتابفروشی',
    people_found_this_helpful: 'نفر این مورد را مفید یافتند',
    people_found_this_helpful_1: 'نفر این مورد را مفید یافت',
    people_report_this: 'نفر این مورد را گزارش کردند',
    people_report_this_1: 'نفر این مورد را گزارش کرد',
    helpful: 'مفید است',
    report: 'گزارش',
    see_all_n_reviews: 'دیدن همه {0} نظر',
    write_a_review: 'یک نظر بگذارید',
    n_out_of_m_stars: '{0} از {1} ستاره',
    bookstore_books: 'کتاب های کتابفروشی',
    best_seller: 'پرفروش ها',
    more_to_explore: 'بیشتر برای کاوش',
    all: 'همه',
    downloaded: 'دانلود شده',
    more_reviews: 'نظرات بیشتر',
    thank_you_for_your_feedback: 'با تشکر از بازخورد شما',
    inspired_by_your_wishlist: 'با توجه به لیست علاقه مندی ها شما',
    uncollected: 'بدون دسته',
    from: 'از',
    to: 'تا',
    customer_reviews: 'نظرات مشتری ها',
    by_writerName: 'از',
    agent: 'نماینده',
    previous: 'قبلی',
    next: 'بعدی',
    no_item_found: 'موردی یافت نشد',
    category: {
        category: 'گروه',
        new: 'نسخه ها جدید',
        best_seller: 'پرفروش ها',
        recommended: 'پیشنهادی برای شما',
        wishlist: 'لیست علاقه مندی ها',

        romance: 'عاشقانه',
        classic: 'کلاسیک',
        comedy: 'کمدی',
        drama: 'درام',
        historical: 'تاریخی',
        religious: 'مذهبی',
        science: 'علمی',
        social: 'اجتماعی',
    },
    load_more: 'بارگذاری بیشتر',
    book_isben: 'شابک',
    your_comment: 'نظر شما',
    remove: 'حذف',
    your_report_submited: 'گزارش شما ثبت شد',
    vote: 'رای',
    vote_s: 'رای',
    votes: 'آراء',
    remove_from_list: 'از لیست حذف کن',
    recent_reviews: 'نظرات اخیر',
    minute: 'دقیقه',
    hour: 'ساعت',
    remove_comment: 'حذف نظر',
    close: 'بستن',
    app_info: 'اطلاعات برنامه',
    version: 'نسخه',
    version_mode: 'نوع نسخه',
    trial_mode: 'نسخه آزمایشی',
    trial: 'آزمایشی',
    dont_want_now: "فعلا نمی خواهم",
    update: 'بروزرسانی',
    new:"جدید",
    book:"کتاب",
    edition:"ویرایش",
    duration:"مدت زمان",
    genre:"ژانر",
    type :"نوع",
    tags:"برچسب ها",
    roles:"نقش ها",
    role:"نقش",
    images:"تصاویر",
    images_list:"لیست تصاویر",
    person:"شخص",
    DRAG_AND_DROP:"بکشید و رها کنید",
    create_book:"ایجاد کتاب",
    edit_book:"ویرایش کتاب",
    book_manage:"مدیریت کتاب",
    dashboard:"پیشخوان",
    price:"قیمت",
    Pricing:"قیمت گذاری",
    Add_price:"افزودن قیمت",
    Justـenterـtheـnumericـvalue:"فقط مقدار عددی وارد نمایید",
    email:"ایمیل",
    cell_no:"تلفن همراه",
    person_manage:"مدیریت شخص",
    image:"تصویر",
    create_person:"ایجاد شخص",
    person_update: "بروزرسانی شخص",
    edit_person:"ویرایش شخص",
    profile:"پروفایل",
    profile_image:"تصویر پروفایل",
    full_name:"نام و نام خانوادگی",
    preview:"پیش نمایش",
    name_or_lastname:"نام یا نام خانوادگی",
    user:"کاربر",
    create_user:"ایجاد کاربر",
    user_update:"بروزرسانی کاربر",
    comment:"نظر",
    book_title:"عنوان کتاب",
    number_of_likes:"تعداد پسندها",
    number_of_reports:"تعداد گزارشات",
    book_image:"تصویر کتاب",
    book_type:"نوع کتاب",
    liked_by_user:"پسندشده توسط کاربر",
    reported_by_user:"گزارش شده توسط کاربر",
    show_comment:"نمایش نظر",
    order:"سفارش",
    create_order:"ایجاد سفارش",
    order_update:"بروزرسانی سفارش",
    status:"وضعیت",
    total_price:"قیمت کل",
    Customer_Specifications:"مشخصات سفارش دهنده",
    count:"تعداد",
    Total_purchase:"مجموع خرید",
    invoice:"فاکتور",
    recalculate:"محاسبه مجدد",
    creation_date:"تاریخ ایجاد",
    Quick_person_creation:"ایجاد سریع شخص",
    type_of_report:{
        Reporting_Period:"دوره زمانی گزارش",
        monthly:"ماهانه",
        weekly:"هفتگی",
    },
    type_of_report_kind:{
        most_Selling:"بیشترین فروش",
        lowest_selling:"کمترین فروش",
        both:"هر دو",
    },
    annual_Reports:{
        spring:"بهار",
        summer:"تابستان",
        fall:"پائیز",
        winter:"زمستان",
        last_quarter:"سه ماهه اخیر",
        yearly:"سالانه",
    },
    name_of_report:{
        ten_Recent_Comments : "10 کامنت اخیر",
        The_best_selling_and_least_selling_of_recent_weeks_and_months : "پرفروش ترین و کم فروش ترین یک هفته - ماه اخیر",
        fifteen_books_have_recently_been_sold_by_type : "15 کتاب فروش رفته اخیر به تفکیک نوع",
        Monthly_sale_seasonal_and_yearly : "فروش ماهانه - فصلی و سالانه",
        Compare_publishers_sales_by_time_period : "مقایسه فروش ناشرین به تفکیک دوره زمانی",
        User_to_customer_conversion_process_chart:"نمودار فرآیند تبدیل کاربر به مشتری",
    },
    genre_type_list:{
        Comedy:"کمدی",
        Drama:"درام",
        Romance:"عاشقانه",
        Social:"اجتماعی",
        Religious:"دینی",
        Historical:"تاریخی",
        Classic:"کلاسیک",
        Science:"علمی",
    },
    book_type_list:{
        DVD: 'دی وی دی',
        Audio: 'صوتی',
        Hard_Copy: 'چاپی',
        Pdf: 'پی دی اف',
        Epub: 'Epub'
    },
    role_type_list: {
        Author: 'مولف',
        Writer : 'نویسنده',
        Translator : 'مترجم',
        Press : 'مطبوعات',
        Contributer : 'مشارکت کننده',
        Designer : 'طراح',
    },
    validation_msg: {
        Just_enter_the_phone_number : "فقط شماره تلفن وارد کنید",
        Just_enter_the_cell_number :"فقط شماره موبایل وارد کنید",
        Just_enter_the_email :"فقط ایمیل وارد کنید",
        Just_enter_the_numeric_value :"فقط مقدار عددی وارد کنید",
        just_one_image_person_can_have:"تنها می توانید یک تصویر بارگذاری کنید لطفا عکس قبلی را حذف کنید",
        file_can_not_added:"فایل اضافه نشد",
    },
}