export const en = {
    login: "login",
    register: "register",
    sign_in: 'sign in',
    app_title: 'book store managment',
    app_title_: 'app title',
    app_logo: 'bookstore',
    brand_name: 'bookstore',
    sign_in_bookstore_account: 'sign in with your bookstore account',
    forgot_password: 'forgot password?',
    stop : 'stop',
    cancel : 'cancel',
    build : 'build',
    msg: {
        ui: {
            msg1: 'action succeeded',
            msg2: 'error occurred',
            msg3: 'registered successfully, we redirect you to login page.',
            msg4: 'password changed successfully, we redirect you to login page.',
            msg5 : 'an error occurred try again.',
            your_rate_submited: 'your rate submited',
            your_comment_submited: 'your comment submited',
            your_comment_will_be_removed_continue: 'your comment will be removed, continue?',
            no_network_connection: 'error occurred, please check your network connection and try again',
            new_vesion_available_update: 'new vesion of app is available, you can update it.',
            item_will_be_removed_continue: 'item will be removed continue?',
            you_stop_uploading_process : 'you stoped the upload process',
            upload_process_error_msg : 'there is error in upload process',
            do_you_want_create_this_book_content : 'do you want build this book content ?',
            admin_book_content_generate:{
                chapter_title_cannot_be_blank : 'chapter title cannot be blank.',
                chapter_title_and_content_cannot_be_blank : 'chapter title and content cannot be blank.',
                just_one_file_can_upload : 'You can only upload a file Please delete the previous file.',
                book_not_created : 'This book has not been created yet.',
                before_generate_request_result_pendding: 'Due to a previous request, the book creation process is in progress, please wait for the server response ...',
                before_generate_request_result_fail: 'An error occurred while trying to create the previous book. Please try again.',
                before_generate_request_result_success: 'The book creation process has already been successfully completed.',
                after_generate_request_result_pendding: 'Book creation process in progress Please wait for server response ...',
                after_generate_request_result_fail: 'Your current request to create the book has encountered an error. Please try again.',
                after_generate_request_result_success: 'Book creation process completed successfully.',
                content_status_query_error_try_again : 'Error in content status query, please try again.',
                Inquiring :'Inquiring ...',
            }
        },
        back: {
            user_already_exists: 'user already exists',
            no_valid_activation_code: 'your activation code has expired, please click resend to reseive new one.',
            wrong_activation_code: 'activation code is invalid',
            already_has_valid_key: 'sending sms will active for you in {0} second',
            message_not_sent: 'error occuerd while sending sms, please try again.',
            cell_no_required: 'cell number is required',
            message_sent: 'message sent to cell number successfully',
            username_exists: 'username already exists.please choose another one',
            signup_token_not_exists: 'Your registration has expired, please start the registration process from the beginning.',
            invalid_signup_token: 'Your registration has expired, please start the registration process from the beginning.',
            token_invalid: 'login again',
            token_expired: 'token expired',
            delete_failed: 'deleting failed',
            get_failed: 'getting failed',
            auth_decoding_failed: 'Authentication decoding failed',
            commit_failed: 'commiting to database failed',
            no_auth: 'you are not logged in',
            invalid_username: 'username or password is not valid',
            invalid_enum: 'enum is not correct  type',
            not_found: 'entity not found',
            invalid_persons: 'there is invalid person id in list',
            addition_error: 'adding model to database failed',
            username_cellno_required: 'for retrieving password username or cell number must send',
            invalid_user: "the user by this data doesn't exist",
            invalid_code: 'the code is invalid',

            filter_required: 'filter object is not in data',
            upload_failed: 'uploading files encountered a problem',
            invalid_entity: 'entity is not right instance of Class',
            access_denied: 'user has not access to this action',
            already_liked: 'user already liked this comment',
            comment_not_found: 'comment not found',
            already_reported: ' user already reported the comment',
            report_not_found: 'report by this user for this comment not found',
            parent_not_found: 'parent object cant found',
            follow_denied: 'user cant follow him/her self',
            already_follows: 'user already follows target',
            missing_requiered_field: 'missing requiered field',
            already_rated: 'user already rated to book',
            already_exists: 'entity already exists',
            credit_debit_error: 'credit and debit can not have amount at the same time',
            no_price_found: 'there is no price for this book in our tables',
            discount_is_float: 'discount should be sent in float format',
            insufficiant_balance: 'your account value is lower than your reciept',
            user_has_no_account: 'user has no account',
            order_invoiced: 'order is invoiced and not deletable',
            commit_error: 'error while commiting in db',
            person_has_books: 'person already has roles for books',
            book_not_in_lib: 'book is not in users library and cannot add to a collection',
            used_somewhere :'The row cannot be deleted due to use.',
        }
    },
    validation: {
        minLength: 'min length {value} character',
        mobileFormat: 'mobile format is not valid',
        smsCodeFormat: 'code is not valid.',
        confirmPassword: 'confirm password not match password.',
        emailFormat: 'email format is not valid',
        phoneFormat: 'phone format is not valid',
    },
    username: 'username',
    password: 'password',
    name: 'name',
    lastname: 'last name',
    phone: 'phone',
    address: 'address',
    mobile: 'mobile',
    confirm_password: 'confirm password',
    invalid_value: 'invalid value',
    required_field: 'required field',
    Show_password: 'Show password',
    login_agree_msg: {
        a: 'By tapping "Sign in" you agree to the {0} {1}',
        b: 'Bookstore Content',
        c: 'and Software Terms of Use'
    },
    new_to_Bookstore: 'new to Bookstore?',
    need_free_bookstore_account: "You'll need a free Bookstore account to sign in.",
    register_your_mobile_number: 'Register your mobile number',
    submit: 'submit',
    already_have_bookstore_account: 'already have bookstore account?',
    verification_code_sended_via_sms_submit_here: 'verification code sended via sms, submit here.',
    verification_code: 'verification code',
    create_an_account: 'create an account',
    send_again: 'send again',
    send_again_activationCode: 'send again activation code',
    in: 'in',
    second: 'second',
    search: 'search',
    home: 'home',
    library: 'library',
    store: 'store',
    more: 'more',
    recomended_for_you: 'recomended for you',
    new_release_in_bookstore: 'new release in bookstore',
    more_by_writer: 'more by {0}',
    helen_hardet: 'helen hardet',
    it_will_be_launched_soon: 'it will be launched soon.',

    read_now: 'read now',
    view_in_store: 'view in store',
    add_to_collection: 'add to collection',
    mark_as_read: 'mark as read',
    share_progress: 'share progress',
    recommend_this_book: 'recommend this book',
    remove_from_device: 'remove from device',
    remove_from_home: 'remove from home',
    loading_with_dots: 'loading...',
    retry: 'retry',
    title: 'title',
    return: 'return',
    insert_username_or_mobile: 'insert your username or mobile number',
    reset_password: 'reset password',
    add_to_list: 'add to list',
    log_out: 'log out',
    sync: 'sync',
    read_listen_with_audible: 'read & listen with audible',
    book_update: 'Book Update',
    create: "Create",
    reset: "reset",
    back: "back",
    reading_insights: 'reading insights',
    settings: 'settings',
    info: 'info',
    help_feedback: 'help and feedback',
    about_bookstore_edition: 'about the bookstore edition',
    Length: 'Length',
    pages: 'pages',
    from_the_editor: 'from the editor',
    about_this_item: 'about this item',

    description: 'description',
    product_description: 'product description',
    review: 'review',
    reviews: 'reviews',
    review_s: 'reviews',
    about_the_author: 'about the author',
    features_details: 'features details',
    product_details: 'product details',
    publication_date: 'publication date',
    publisher: 'publisher',
    language: 'language',
    bookstore_sales_rank: 'bookstore sales rank',
    follow: 'follow',
    unfollow: 'unfollow',
    customer_review: 'customer review',
    customer_vote_s: 'customer votes',
    read_reviews_that_mention: 'read reviews that mention',
    see_more: 'see more',
    see_less: 'see less',
    top_reviews: 'top reviews',
    verified_purchase: 'verified_purchase',
    format: 'format',
    bookstore_edition: 'bookstore_edition',
    people_found_this_helpful: 'people found this helpful',
    people_found_this_helpful_1: 'person found this helpful',
    people_report_this: 'people report this',
    people_report_this_1: 'person report this',
    helpful: 'helpful',
    report: 'report',
    see_all_n_reviews: 'see all {0} reviews',
    write_a_review: 'write a review',
    n_out_of_m_stars: '{0} out of {1} stars',
    bookstore_books: 'bookstore books',
    best_seller: 'best seller',
    more_to_explore: 'more to explore',
    all: 'all',
    downloaded: 'downloaded',
    more_reviews: 'more reviews',
    thank_you_for_your_feedback: 'thank you for your feedback',
    inspired_by_your_wishlist: 'inspired by your wishlist',
    uncollected: 'uncollected',
    from: 'from',
    to: 'to',
    customer_reviews: 'customer reviews',
    by_writerName: 'by',
    agent: 'agent',
    previous: 'previous',
    next: 'next',
    no_item_found: 'no item found',
    category: {
        category: 'category',
        new: 'new release',
        best_seller: 'best seller',
        recommended: 'recommended',
        wishlist: 'wishlist',

        romance: 'romance',
        classic: 'classic',
        comedy: 'comedy',
        drama: 'drama',
        historical: 'historical',
        religious: 'religious',
        science: 'science',
        social: 'social',
    },
    load_more: 'load more',
    book_isben: 'asin',
    your_comment: 'your comment',
    remove: 'remove',
    your_report_submited: 'your report submited',
    vote: 'vote',
    vote_s: 'vote',
    votes: 'votes',
    remove_from_list: 'remove from list',
    recent_reviews: 'recent reviews',
    minute: 'minute',
    hour: 'hour',
    remove_comment: 'remove comment',
    close: 'close',
    app_info: 'app info',
    version: 'version',
    version_mode: 'version mode',
    trial_mode: 'trial mode',
    trial: 'trial',
    dont_want_now: "i don't want now",
    update: 'update',
    new: "new",
    book: "book",
    edition: "edition",
    duration: "duration",
    genre: "genre",
    type: "type",
    tags: "tags",
    roles: "roles",
    role: "role",
    images: "images",
    images_list: "images list",
    person: "person",
    legal_person:'legal person',
    real_person : 'real person',
    DRAG_AND_DROP: "DRAG AND DROP",
    create_book: "Create a book",
    edit_book: "Edit the book",
    book_manage: "Book Management",
    dashboard: "dashboard",
    price: "price",
    Pricing: "Pricing",
    Add_price: "Add price",
    Justـenterـtheـnumericـvalue: "Just enter the numeric value",
    email: "email",
    cell_no: "cell_no",
    person_manage: "Person management",
    image: "image",
    create_person: "Create a person",
    person_update: "Person update",
    edit_person: "Edit the person",
    profile: "profile",
    profile_image: "profile image",
    full_name: "full name",
    preview: "preview",
    name_or_lastname: "name or lastname",
    user: "user",
    create_user: "Create a user",
    user_update: "user update",
    comment: "comment",
    book_title: "book's title",
    number_of_likes: "number of likes",
    number_of_reports: "number of reports",
    book_image: "book's image",
    book_type: "book's type",
    liked_by_user: "liked by user",
    reported_by_user: "reported by user",
    show_comment: "show comment",
    order: "order",
    create_order: "Create a order",
    order_update: "order update",
    show_order: 'show order',
    status: "status",
    total_price: "total price",
    Customer_Specifications: "Customer Specifications",
    count: "count",
    Total_purchase: "Total purchase",
    invoice: "invoice",
    recalculate: "recalculate",
    creation_date: "creation date",
    Quick_person_creation: "Quick person creation",
    group: "group",
    create_group: "Create a group",
    group_update: "group update",
    permission: "permission",
    create_permission: "Create a permission",
    permission_update: "permission update",
    creator: "creator",
    modifier : 'modifier',
    modification_date: "modification_date",
    each_book_must_have_only_one_publisher_and_it_is_not_possible_to_add_a_book_without_a_publisher: "Each book must have only one publisher and it is not possible to add a book without a publisher",
    name_of_organization: "name of organization",
    upload : 'upload',
    content : 'content',
    Original: 'original',
    Brief : 'brief',
    NEW_PAGE : 'new page',
    NEW_LINE : 'new line',
    chapter : 'chapter',
    first_Chapter : 'first chapter',
    text : 'text',
    control : 'control',
    voice : 'voice file',
    selected_range_is_not_valid : 'selected range invalid',
    save : 'save',
    content_generated : 'content generated',
    content_not_generated : 'content not generated',
    row : 'row',
    advanced_search : 'advanced search',
    transaction : 'transaction',
    transaction_amount : 'transaction amount',
    increase_credit : 'increase credit',
    reduce_credit : 'reduce credit',
    credit_level : 'credit level',
    no_credit_account_has_been_registered_for_this_person : 'no credit account has been registered for this person.',
    none : 'none',
    type_of_report: {
        Reporting_Period: "Reporting Period",
        monthly: "monthly",
        weekly: "weekly",
    },
    type_of_report_kind: {
        most_Selling: "most_Selling",
        lowest_selling: "Lowest selling",
        both: "both",
    },
    annual_Reports: {
        spring: "spring",
        summer: "summer",
        fall: "fall",
        winter: "winter",
        last_quarter: "last_quarter",
        yearly: "yearly",
    },
    book_generator : {
        addSubChapter : 'add subchapter',
        addChapterBefore: 'add subchapter to before',
        addChapterAfter: 'add subchapter to after',
        addTitleAndContentToChapter: 'add title & content',
        addContent: 'add content',
        addContentBefore: 'add content to before',
        addContentAfter: 'add content to after',
    },
    name_of_report: {
        ten_Recent_Comments: "10 Recent Comments",
        The_best_selling_and_least_selling_of_recent_weeks_and_months: "The best selling and least selling of recent weeks and months",
        fifteen_books_have_recently_been_sold_by_type: "15 books have recently been sold by type",
        Monthly_sale_seasonal_and_yearly: "Monthly sales - seasonal and yearly",
        Compare_publishers_sales_by_time_period: "Compare publishers'sales by time period",
        Order_to_customer_conversion_process_chart: "Order-to-customer conversion process chart",
    },
    languages_list:{
        PERSIAN : 'Persian',
        ENGLISH : 'English',
        ARABIC : 'Arabic',
        FRENCH : 'French',
        GERMAN : 'German',
        SPANISH : 'Spanish',
    },
    genre_type_list: {
        Comedy: "comedy",
        Drama: "drama",
        Romance: "romance",
        Social: "social",
        Religious: "religious",
        Historical: "historical",
        Classic: "classic",
        Science: "science",
    },
    book_type_list: {
        DVD: 'DVD',
        Audio: 'Audio',
        Hard_Copy: 'Hard_Copy',
        Pdf: 'Pdf',
        Epub: 'Epub',
        Msd : 'bookstore'
    },
    role_type_list: {
        Author: 'Author',
        Writer: 'Writer',
        Translator: 'Translator',
        Press: 'Press',
        Contributer: 'Contributer',
        Designer: 'Designer',
        Narrator : 'Narrator',
    },
    permissions_list: {
        IS_OWNER : 'is owner',
        ACCOUNT_ADD_PREMIUM : 'add account(premium)',
        ACCOUNT_EDIT_PREMIUM : 'edit account(premium)',
        ACCOUNT_DELETE_PREMIUM : 'delete account(premium)',
        ACCOUNT_GET_PREMIUM : 'get account(premium)',
    
        LIBRARY_ADD_PREMIUM : 'LIBRARY_ADD_PREMIUM',
        LIBRARY_EDIT_PREMIUM : 'LIBRARY_EDIT_PREMIUM',
        LIBRARY_DELETE_PREMIUM : 'LIBRARY_DELETE_PREMIUM',
        LIBRARY_GET_PREMIUM : 'LIBRARY_GET_PREMIUM',
    
        RATE_DELETE_PREMIUM : 'RATE_DELETE_PREMIUM',
        RATE_EDIT_PREMIUM : 'RATE_EDIT_PREMIUM',
    
        BOOK_ADD_PREMIUM : 'BOOK_ADD_PREMIUM',
        BOOK_EDIT_PREMIUM : 'BOOK_EDIT_PREMIUM',
        BOOK_DELETE_PREMIUM : 'BOOK_DELETE_PREMIUM',
        BOOK_ADD_PRESS : 'BOOK_ADD_PRESS',
        BOOK_EDIT_PRESS : 'BOOK_EDIT_PRESS',
        BOOK_DELETE_PRESS : 'BOOK_DELETE_PRESS',
        BOOK_CONTENT_ADD_PREMIUM : 'BOOK_CONTENT_ADD_PREMIUM',
        BOOK_CONTENT_ADD_PRESS : 'BOOK_CONTENT_ADD_PRESS',
        BOOK_CONTENT_GET_PREMIUM : 'BOOK_CONTENT_GET_PREMIUM',
        BOOK_CONTENT_GET_PRESS : 'BOOK_CONTENT_GET_PRESS',
    
        COMMENT_ADD_PREMIUM : 'COMMENT_ADD_PREMIUM',
        COMMENT_EDIT_PREMIUM : 'COMMENT_EDIT_PREMIUM',
        COMMENT_DELETE_PREMIUM : 'COMMENT_DELETE_PREMIUM',
        COMMENT_GET_PREMIUM : 'COMMENT_GET_PREMIUM',
        COMMENT_ADD : 'COMMENT_ADD',
        COMMENT_EDIT : 'COMMENT_EDIT',
        COMMENT_DELETE : 'COMMENT_DELETE',
        COMMENT_GET : 'COMMENT_GET',
        COMMENT_DELETE_PRESS : 'COMMENT_DELETE_PRESS',
    
        TRANSACTION_ADD_PREMIUM : 'TRANSACTION_ADD_PREMIUM',
        TRANSACTION_DELETE_PREMIUM : 'TRANSACTION_DELETE_PREMIUM',
        TRANSACTION_GET_PREMIUM : 'TRANSACTION_GET_PREMIUM',
    
        COMMENT_ACTION_DELETE_PREMIUM : 'COMMENT_ACTION_DELETE_PREMIUM',
        COMMENT_ACTION_DELETE_PRESS : 'COMMENT_ACTION_DELETE_PRESS',
    
        FOLLOW_DELETE_PREMIUM : 'FOLLOW_DELETE_PREMIUM',
    
        ORDER_CHECKOUT_PREMIUM : 'ORDER_CHECKOUT_PREMIUM',
        ORDER_ADD_PREMIUM : 'ORDER_ADD_PREMIUM',
        ORDER_ADD_PRESS : 'ORDER_ADD_PRESS',
        ORDER_GET_PREMIUM : 'ORDER_GET_PREMIUM',
        ORDER_EDIT_PREMIUM : 'ORDER_EDIT_PREMIUM',
        ORDER_DELETE_PREMIUM : 'ORDER_DELETE_PREMIUM',
    
        ORDER_ITEM_GET_PREMIUM : 'ORDER_ITEM_GET_PREMIUM',
        ORDER_ITEM_EDIT_PREMIUM : 'ORDER_ITEM_EDIT_PREMIUM',
        ORDER_ITEM_DELETE_PREMIUM : 'ORDER_ITEM_DELETE_PREMIUM',
    
        PRICE_ADD_PREMIUM : 'PRICE_ADD_PREMIUM',
        PRICE_GET_PREMIUM : 'PRICE_GET_PREMIUM',
        PRICE_EDIT_PREMIUM : 'PRICE_EDIT_PREMIUM',
        PRICE_DELETE_PREMIUM : 'PRICE_DELETE_PREMIUM',
        PRICE_ADD_PRESS : 'PRICE_ADD_PRESS',
        PRICE_EDIT_PRESS : 'PRICE_EDIT_PRESS',
        PRICE_DELETE_PRESS : 'PRICE_DELETE_PRESS',
    
        PERSON_ADD_PREMIUM : 'PERSON_ADD_PREMIUM',
        PERSON_EDIT_PREMIUM : 'PERSON_EDIT_PREMIUM',
        PERSON_DELETE_PREMIUM : 'PERSON_DELETE_PREMIUM',
        PERSON_GET_PREMIUM : 'PERSON_GET_PREMIUM',
    
        USER_DELETE_PREMIUM : 'USER_DELETE_PREMIUM',
        USER_GET_PREMIUM : 'USER_GET_PREMIUM',
        USER_EDIT_PREMIUM : 'USER_EDIT_PREMIUM',
    
        DISCUSSION_GROUP_PREMIUM : 'DISCUSSION_GROUP_PREMIUM',
        DISCUSSION_MEMBER_PREMIUM : 'DISCUSSION_MEMBER_PREMIUM',
    
        CHAT_DELETE_PREMIUM : 'CHAT_DELETE_PREMIUM',
        CHAT_GET_PREMIUM : 'CHAT_GET_PREMIUM',
        CHAT_EDIT_PREMIUM : 'CHAT_EDIT_PREMIUM',
    
        PAYMENT_ADD_PREMIUM : 'PAYMENT_ADD_PREMIUM',
        PAYMENT_ADD_PRESS : 'PAYMENT_ADD_PRESS',
        PAYMENT_GET_PREMIUM : 'PAYMENT_GET_PREMIUM',
    
        DEVICE_KEY_ADD_PREMIUM : 'DEVICE_KEY_ADD_PREMIUM',
        DEVICE_KEY_GET_PREMIUM : 'DEVICE_KEY_GET_PREMIUM',
        DEVICE_KEY_DELETE_PREMIUM : 'DEVICE_KEY_DELETE_PREMIUM',
    
        PREPARE_BOOK_PREMIUM : 'PREPARE_BOOK_PREMIUM',
    },
    order_status: {
        Invoiced: 'invoiced',
        Created: 'created',
    },
    validation_msg: {
        Just_enter_the_phone_number: "Just enter the phone number",
        Just_enter_the_cell_number: "Just enter the mobile number",
        Just_enter_the_email: "Just enter the email",
        Just_enter_the_numeric_value: "Just enter the numeric value",
        just_one_image_person_can_have: "You can only upload an image Please delete the previous image",
        file_can_not_added: "file can not be added.",
    },
}