export const en = {
    login: "login",
    register: "register",
    sign_in: 'sign in',
    app_title: 'book store',
    app_title_: 'app title',
    app_logo: 'bookstore',
    brand_name: 'bookstore',
    sign_in_bookstore_account: 'sign in with your bookstore account',
    forgot_password: 'forgot password?',
    msg: {
        ui: {
            msg1: 'action succeeded',
            msg2: 'error occurred',
            msg3: 'registered successfully, we redirect you to login page.',
            msg4: 'password changed successfully, we redirect you to login page.',
            your_rate_submited: 'your rate submited',
            your_comment_submited: 'your comment submited',
            your_comment_will_be_removed_continue: 'your comment will be removed, continue?',
            no_network_connection: 'error occurred, please check your network connection and try again',
            new_vesion_available_update: 'new vesion of app is available, you can update it.',
            item_will_be_removed_continue: 'item will be removed continue?',
        },
        back: {
            msg1: 'user already exists',
            msg2: 'your activation code has expired, please click resend to reseive new one.',
            msg3: 'activation code is invalid',
            msg4: 'sending sms will active for you in {0} second',
            msg5: 'error occuerd while sending sms, please try again.',
            msg6: 'cell number is required',
            msg7: 'message sent to cell number successfully',
            msg8: 'username already exists.please choose another one',
            msg9: 'Your registration has expired, please start the registration process from the beginning.',
            msg10: 'Your registration has expired, please start the registration process from the beginning.',

            msg11: 'login again', // token invalid
            msg12: 'token expired',
            msg13: 'deleting failed',
            msg14: 'getting failed',
            msg15: 'Authentication decoding failed',
            msg16: 'commiting to database failed',
            msg17: 'you are not logged in',
            msg18: 'username or password is not valid',

            msg19: 'enum is not correct  type',
            msg20: 'entity not found',
            invalid_persons: 'there is invalid person id in list',
            addition_error: 'adding model to database failed',

            username_cellno_required: 'for retrieving password username or cell number must send',
            invalid_user: "the user by this data doesn't exist",

            invalid_code: 'the code is invalid',

        }
    },
    validation: {
        minLength: 'min length {value} character',
        mobileFormat: 'mobile format is not valid',
        smsCodeFormat: 'code is not valid.',
        confirmPassword: 'confirm password not match password.',
    },
    username: 'username',
    password: 'password',
    name: 'name',
    lastname: 'last name',
    phone: 'phone',
    address: 'address',
    mobile: 'mobile',
    confirm_password: 'confirm password',
    invalid_value: 'invalid value',
    required_field: 'required field',
    Show_password: 'Show password',
    login_agree_msg: {
        a: 'By tapping "Sign in" you agree to the {0} {1}',
        b: 'Bookstore Content',
        c: 'and Software Terms of Use'
    },
    new_to_Bookstore: 'new to Bookstore?',
    need_free_bookstore_account: "You'll need a free Bookstore account to sign in.",
    register_your_mobile_number: 'Register your mobile number',
    submit: 'submit',
    already_have_bookstore_account: 'already have bookstore account?',
    verification_code_sended_via_sms_submit_here: 'verification code sended via sms, submit here.',
    verification_code: 'verification code',
    create_an_account: 'create an account',
    send_again: 'send again',
    send_again_activationCode: 'send again activation code',
    in: 'in',
    second: 'second',
    search: 'search',
    home: 'home',
    library: 'library',
    store: 'store',
    more: 'more',
    recomended_for_you: 'recomended for you',
    new_release_in_bookstore: 'new release in bookstore',
    more_by_writer: 'more by {0}',
    helen_hardet: 'helen hardet',
    it_will_be_launched_soon: 'it will be launched soon.',

    read_now: 'read now',
    view_in_store: 'view in store',
    add_to_collection: 'add to collection',
    mark_as_read: 'mark as read',
    share_progress: 'share progress',
    recommend_this_book: 'recommend this book',
    remove_from_device: 'remove from device',
    remove_from_home: 'remove from home',
    loading_with_dots: 'loading...',
    retry: 'retry',
    title: 'title',
    return: 'return',
    insert_username_or_mobile: 'insert your username or mobile number',
    reset_password: 'reset password',
    add_to_list: 'add to list',
    log_out: 'log out',
    sync: 'sync',
    read_listen_with_audible: 'read & listen with audible',
    book_update: 'Book Update',
    create: "Create",
    reset: "reset",
    back: "back",
    reading_insights: 'reading insights',
    settings: 'settings',
    info: 'info',
    help_feedback: 'help and feedback',
    about_bookstore_edition: 'about the bookstore edition',
    Length: 'Length',
    pages: 'pages',
    from_the_editor: 'from the editor',
    about_this_item: 'about this item',

    description: 'description',
    product_description: 'product description',
    review: 'review',
    reviews: 'reviews',
    review_s: 'reviews',
    about_the_author: 'about the author',
    features_details: 'features details',
    product_details: 'product details',
    publication_date: 'publication date',
    publisher: 'publisher',
    language: 'language',
    bookstore_sales_rank: 'bookstore sales rank',
    follow: 'follow',
    unfollow: 'unfollow',
    customer_review: 'customer review',
    customer_vote_s: 'customer votes',
    read_reviews_that_mention: 'read reviews that mention',
    see_more: 'see more',
    see_less: 'see less',
    top_reviews: 'top reviews',
    verified_purchase: 'verified_purchase',
    format: 'format',
    bookstore_edition: 'bookstore_edition',
    people_found_this_helpful: 'people found this helpful',
    people_found_this_helpful_1: 'person found this helpful',
    people_report_this: 'people report this',
    people_report_this_1: 'person report this',
    helpful: 'helpful',
    report: 'report',
    see_all_n_reviews: 'see all {0} reviews',
    write_a_review: 'write a review',
    n_out_of_m_stars: '{0} out of {1} stars',
    bookstore_books: 'bookstore books',
    best_seller: 'best seller',
    more_to_explore: 'more to explore',
    all: 'all',
    downloaded: 'downloaded',
    more_reviews: 'more reviews',
    thank_you_for_your_feedback: 'thank you for your feedback',
    inspired_by_your_wishlist: 'inspired by your wishlist',
    uncollected: 'uncollected',
    from: 'from',
    to: 'to',
    customer_reviews: 'customer reviews',
    by_writerName: 'by',
    agent: 'agent',
    previous: 'previous',
    next: 'next',
    no_item_found: 'no item found',
    category: {
        category: 'category',
        new: 'new release',
        best_seller: 'best seller',
        recommended: 'recommended',
        wishlist: 'wishlist',

        romance: 'romance',
        classic: 'classic',
        comedy: 'comedy',
        drama: 'drama',
        historical: 'historical',
        religious: 'religious',
        science: 'science',
        social: 'social',
    },
    load_more: 'load more',
    book_isben: 'asin',
    your_comment: 'your comment',
    remove: 'remove',
    your_report_submited: 'your report submited',
    vote: 'vote',
    vote_s: 'vote',
    votes: 'votes',
    remove_from_list: 'remove from list',
    recent_reviews: 'recent reviews',
    minute: 'minute',
    hour: 'hour',
    remove_comment: 'remove comment',
    close: 'close',
    app_info: 'app info',
    version: 'version',
    version_mode: 'version mode',
    trial_mode: 'trial mode',
    trial: 'trial',
    dont_want_now: "i don't want now",
    update: 'update',
    new: "new",
    book: "book",
    edition: "edition",
    duration: "duration",
    genre: "genre",
    type: "type",
    tags:"tags",
    roles: "roles",
    role: "role",
    images: "images",
    images_list: "images list",
    person: "person",
    DRAG_AND_DROP: "DRAG AND DROP",
    create_book: "Create a book",
    edit_book: "Edit the book",
    book_manage: "Book Management",
    dashboard: "dashboard",
    price:"price",
    Pricing:"Pricing",
    Add_price:"Add price",
    Justـenterـtheـnumericـvalue:"Just enter the numeric value",
    email:"email",
    cell_no:"cell_no",
    person_manage:"Person management",
    image:"image",
    // money_unit:'$',
    genre_type_list:{
        Comedy: "comedy",
        Drama: "drama",
        Romance: "romance",
        Social: "social",
        Religious: "religious",
        Historical: "historical",
        Classic: "classic",
        Science: "science",
    },
    book_type_list: {
        DVD: 'DVD',
        Audio: 'Audio',
        Hard_Copy: 'Hard_Copy',
        Pdf: 'Pdf',
        Epub: 'Epub'
    },
    role_type_list: {
        Author: 'Author',
        Writer : 'Writer',
        Translator : 'Translator',
        Press : 'Press',
        Contributer : 'Contributer',
        Designer : 'Designer',
    },
}