export const fa = {
    login: "ورود",
    register: "ثبت نام",
    sign_in: 'ورود',
    app_title: 'فروشگاه کتاب',
    app_title_: 'عنوان برنامه',
    app_logo: 'فروشگاه کتاب',
    brand_name: 'فروشگاه کتاب',
    sign_in_bookstore_account: 'با حساب فروشگاه کتاب خود داخل شوید',
    forgot_password: 'رمز عبورتان را فراموش کردید؟',
    msg: {
        ui: {
            msg1: 'عملیات با موفقیت انجام شد.',
            msg2: 'خطا رخ داد.',
            msg3: 'ثبت نام با موفقیت انجام شد، به صفحه ورود منتقل می شوید.',
            msg4: 'رمز عبور با موفقیت تغییر کرد، به صفحه ورود منتقل می شوید.',
            your_rate_submited: 'رتبه شما ثبت شد',
            your_comment_submited: 'نظر شما ثبت شد',
            your_comment_will_be_removed_continue: 'نظر شما حذف خواهد شد، تایید می کنید؟',
            no_network_connection: 'خطا رخ داد، لطفا دسترسی اینترنت خود را بررسی کرده و مجددا تلاش کنید.',
            new_vesion_available_update: 'نسخه جدیدی از برنامه موجود است، می توانید آن را بروز کنید.',
            item_will_be_removed_continue: 'رکورد مورد نظر حذف خواهد شد، تایید می کنید؟',
        },
        back: {
            msg1: 'کاربر از قبل وجود دارد.',
            msg2: 'کد فعالسازی شما منقضی شده است، برای دریافت کد جدید ارسال مجدد را بفشارید.',
            msg3: 'کد فعالسازی اشتباه است.',
            msg4: 'امکان ارسال مجدد پیامک {0} ثانیه دیگر برای شما فعال می شود.',
            msg5: 'ارسال پیامک با خطا مواجه شد، لطفا مجددا تلاش کنید.',
            msg6: 'تلفن همراه الزامی است.',
            msg7: 'پیام با موفقیت برای تلفن همراه ارسال شد.',
            msg8: 'نام کاربری تکراری است، لطفا نام کاربری دیگری انتخاب کنید.',
            msg9: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            msg10: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',

            msg11: 'مجددا وارد شوید', // token invalid
            msg12: 'token expired',
            msg13: 'deleting failed',
            msg14: 'getting failed',
            msg15: 'Authentication decoding failed',
            msg16: 'commiting to database failed',
            msg17: 'شما وارد نشده اید',
            msg18: 'نام کاربری یا رمز عبور اشتباه است.',

            msg19: 'enum is not correct  type',
            msg20: 'مورد، یافت نشد.',
            invalid_persons: 'there is invalid person id in list',
            addition_error: 'adding model to database failed',

            username_cellno_required: 'برای دریافت رمز عبور نام کاربری یا شماره موبایل را وارد کنید',
            invalid_user: "با اطلاعات وارد شده کاربری وجود ندارد",

            invalid_code: 'کد تایید اشتباه است.',
        }
    },
    validation: {
        minLength: 'حداقل {value} کاراکتر',
        mobileFormat: 'فرمت موبایل صحیح نیست',
        smsCodeFormat: 'فرمت کد صحیح نیست.',
        confirmPassword: 'رمز عبور با تایید آن همخوانی ندارد.',
    },
    username: 'نام کاربری',
    password: 'رمز عبور',
    name: 'نام',
    lastname: 'نام خانوادگی',
    phone: 'تلفن',
    address: 'آدرس',
    mobile: 'تلفن همراه',
    confirm_password: 'تایید رمز عبور',
    invalid_value: 'مقدار نامعتبر است',
    required_field: 'فیلد ضروری است',
    Show_password: 'نمایش رمزعبور',
    login_agree_msg: {
        a: 'با انتخاب "ورود" شما موافقت خود با {0} و {1} را تایید می کنید.',
        b: 'مطالب فروشگاه کتاب',
        c: 'شرایط استفاده از نرم افزار'
    },
    new_to_Bookstore: 'تازه واردید؟',
    need_free_bookstore_account: "احتیاج به یک حساب کاربری رایگان فروشگاه کتاب دارید.",
    register_your_mobile_number: 'شماره تلفن همراه خود را وارد کنید',
    submit: 'ثبت',
    already_have_bookstore_account: 'از قبل حساب کاربری فروشگاه کتاب دارید؟',
    verification_code_sended_via_sms_submit_here: 'کد تایید برای شما پیامک شد، لطفا در اینجا ثبت کنید.',
    verification_code: 'کد تایید',
    create_an_account: 'ساخت حساب کاربری',
    send_again: 'ارسال مجدد',
    send_again_activationCode: 'ارسال مجدد کد فعالسازی',
    in: 'در',
    second: 'ثانیه',
    search: 'جستجو',
    home: 'خانه',
    library: 'کتابخانه',
    store: 'فروشگاه',
    more: 'بیشتر',
    recomended_for_you: 'پیشنهادی برای شما',
    new_release_in_bookstore: 'نسخه های جدید در کتابفروشی',
    more_by_writer: 'بیشتر از {0}',
    helen_hardet: 'هلن هاردت',
    it_will_be_launched_soon: 'بزودی راه اندازی خواهد شد.',

    read_now: 'الان بخوان',
    view_in_store: 'نمایش در فروشگاه',
    add_to_collection: 'اضافه کردن به کلکسیون',
    mark_as_read: 'به عنوان خوانده شده علامت بزن',
    share_progress: 'اشتراک گذاری پیشرفت',
    recommend_this_book: 'پیشنهاد دادن کتاب',
    remove_from_device: 'حذف از دستگاه',
    remove_from_home: 'حذف از خانه',
    loading_with_dots: 'درحال بارگذاری...',
    retry: 'تلاش مجدد',
    title: 'عنوان',
    return: 'بازگشت',
    insert_username_or_mobile: 'نام کاربری یا شماره تلفن همراه خود را وارد کنید',
    reset_password: 'تغییر رمز عبور',
    add_to_list: 'به لیست اضافه کن',
    log_out: 'خروج',

    sync: 'همگام سازی',
    read_listen_with_audible: 'خواندن و گوش دادن با صدا',
    book_update: 'بروزرسانی کتاب',
    create:"ایجاد",
    reset:"تنظیم مجدد",
    back:"بازگشت",
    reading_insights: 'خواندن عمیق',
    settings: 'تنظیمات',
    info: 'اطلاعات',
    help_feedback: 'کمک و بازخورد',

    about_bookstore_edition: 'درباره نسخه کتابفروشی',
    Length: 'اندازه',
    pages: 'صفحه',

    from_the_editor: 'از ویراستار',
    about_this_item: 'درباره این محصول',

    description: 'توضیحات',
    product_description: 'توضیحات محصول',
    review: 'نظر',
    reviews: 'نظرات',
    review_s: 'نظر',
    about_the_author: 'درباره نویسنده',
    features_details: 'ویژگی ها و جزئیات',
    product_details: 'جزئیات محصول',
    publication_date: 'تاریخ انتشار',
    publisher: 'ناشر',
    language: 'زبان',
    bookstore_sales_rank: 'رتبه فروش در کتابفروشی',
    follow: 'دنبال کردن',
    unfollow: 'دنبال نکردن',
    customer_review: 'نظر مشتری ها',
    customer_vote_s: 'رای مشتری ها',
    read_reviews_that_mention: 'خواندن نظر های ذکر شده',
    see_more: 'بیشتر ببینید',
    see_less: 'کمتر ببینید',
    top_reviews: 'نظر های برتر',
    verified_purchase: 'خرید تایید شده',
    format: 'قالب',
    bookstore_edition: 'نسخه کتابفروشی',
    people_found_this_helpful: 'نفر این مورد را مفید یافتند',
    people_found_this_helpful_1: 'نفر این مورد را مفید یافت',
    people_report_this: 'نفر این مورد را گزارش کردند',
    people_report_this_1: 'نفر این مورد را گزارش کرد',
    helpful: 'مفید است',
    report: 'گزارش',
    see_all_n_reviews: 'دیدن همه {0} نظر',
    write_a_review: 'یک نظر بگذارید',
    n_out_of_m_stars: '{0} از {1} ستاره',
    bookstore_books: 'کتاب های کتابفروشی',
    best_seller: 'پرفروش ها',
    more_to_explore: 'بیشتر برای کاوش',
    all: 'همه',
    downloaded: 'دانلود شده',
    more_reviews: 'نظرات بیشتر',
    thank_you_for_your_feedback: 'با تشکر از بازخورد شما',
    inspired_by_your_wishlist: 'با توجه به لیست علاقه مندی ها شما',
    uncollected: 'بدون دسته',
    from: 'از',
    to: 'تا',
    customer_reviews: 'نظرات مشتری ها',
    by_writerName: 'از',
    agent: 'نماینده',
    previous: 'قبلی',
    next: 'بعدی',
    no_item_found: 'موردی یافت نشد',
    category: {
        category: 'گروه',
        new: 'نسخه ها جدید',
        best_seller: 'پرفروش ها',
        recommended: 'پیشنهادی برای شما',
        wishlist: 'لیست علاقه مندی ها',

        romance: 'عاشقانه',
        classic: 'کلاسیک',
        comedy: 'کمدی',
        drama: 'درام',
        historical: 'تاریخی',
        religious: 'مذهبی',
        science: 'علمی',
        social: 'اجتماعی',
    },
    load_more: 'بارگذاری بیشتر',
    book_isben: 'شابک',
    your_comment: 'نظر شما',
    remove: 'حذف',
    your_report_submited: 'گزارش شما ثبت شد',
    vote: 'رای',
    vote_s: 'رای',
    votes: 'آراء',
    remove_from_list: 'از لیست حذف کن',
    recent_reviews: 'نظرات اخیر',
    minute: 'دقیقه',
    hour: 'ساعت',
    remove_comment: 'حذف نظر',
    close: 'بستن',
    app_info: 'اطلاعات برنامه',
    version: 'نسخه',
    version_mode: 'نوع نسخه',
    trial_mode: 'نسخه آزمایشی',
    trial: 'آزمایشی',
    dont_want_now: "فعلا نمی خواهم",
    update: 'بروزرسانی',
    new:"جدید",
    book:"کتاب",
    edition:"ویرایش",
    duration:"مدت زمان",
    genre:"ژانر",
    type :"نوع",
    tags:"برچسب ها",
    roles:"نقش ها",
    role:"نقش",
    images:"تصاویر",
    images_list:"لیست تصاویر",
    person:"شخص",
    DRAG_AND_DROP:"بکشید و رها کنید",
    create_book:"ایجاد کتاب",
    edit_book:"ویرایش کتاب",
    book_manage:"مدیریت کتاب",
    dashboard:"پیشخوان",
    price:"قیمت",
    Pricing:"قیمت گذاری",
    Add_price:"افزودن قیمت",
    Justـenterـtheـnumericـvalue:"فقط مقدار عددی وارد نمایید",
    // money_unit:'ریال',
    genre_type_list:{
        Comedy:"کمدی",
        Drama:"درام",
        Romance:"عاشقانه",
        Social:"اجتماعی",
        Religious:"دینی",
        Historical:"تاریخی",
        Classic:"کلاسیک",
        Science:"علمی",
    },
    book_type_list:{
        DVD: 'دی وی دی',
        Audio: 'صوتی',
        Hard_Copy: 'چاپی',
        Pdf: 'پی دی اف',
        Epub: 'Epub'
    },
    role_type_list: {
        Author: 'مولف',
        Writer : 'نویسنده',
        Translator : 'مترجم',
        Press : 'مطبوعات',
        Contributer : 'مشارکت کننده',
        Designer : 'طراح',
    },
}